services: 
  db:
    image: mariadb:11.2.2
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./docker/mariadb/data:/var/lib/mariadb"
    ports:
      - "3306:3306"
    healthcheck:
      test: "healthcheck.sh --su-mysql --connect --innodb_initialized"
      interval: 1s
      timeout: 5s
      retries: 20

  api:
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - "80:3000"
      volumes:
          - .:/app
      environment:
          NODE_ENV: development
          PORT: 3000
          DB_HOST: db
          DB_DATABASE: ${DB_DATABASE}
          DB_USER: ${DB_USER}
          DB_PASSWORD: ${DB_PASSWORD}
      networks:
          - default
      depends_on:
          db:
              condition: service_healthy      
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080


