version: '3'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/app
    env_file:
     - .env
  db:
    image: mariadb:11.2.2
    volumes:
      - './docker/mariadb/data/:/var/lib/mysql/'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
