- name: Install docker
- hosts: web
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Copy docker-compose files
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: /
        mode: "0644"
